- hosts: lb
  tasks:
    - name: install haproxy package
      package:
        name: "haproxy"
        state: present


    - name: conf file in haproxy.conf
      template:
        src: "local.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"


    - name: starting the haproxy services
      service:
        name: "haproxy"
        state: restarted
        enabled: true
